### ISSUE TITLE
Further ControlPacket Specifications

### ISSUE THREAD

**Issue by jamesadevine** [jacdac/jacdac#12]
# Device Names
The ability to name devices would make device identification easier for users. I think we should incorporate a optional name into ControlPacket's, the presence of the name would be indicated by a flag in the device_flags field of the ControlPacket:

```cpp
struct JDControlPacket
    {
        uint64_t serial_number;
        uint8_t device_address;
        uint8_t device_flags; (name flag)
        uint8_t name_size; (optional)
        uint8_t name[name_size]; (optional)
        uint8_t data[];
    } __attribute((__packed__));
```

The size of the name will be limited by the how much payload is placed into the ControlPackets->data field.

# ServiceInformation Advertisement Data

The ServiceInformation structure which is embedded inside the ControlPackets->data field has room for an optional advertisement payload:

```cpp
struct JDServiceInfo
    {
        uint32_t service_class;
        uint8_t service_flags; 
        uint8_t advertisement_size;
        uint8_t advertisement_data[]; // optional additional data
    } __attribute((__packed__));
```

In the spec the advertisement size is limited to 15 bytes, but this size is arbitrary and limiting especially if a device is only hosting one service.

I propose that the advertisement data, like the optional name field, will be limited by the amount of payload placed into the ControlPacket->data field.

The developer must ensure that the ServiceInformation for all hosted services are able to fit inside the 255 byte payload of a JACDAC packet.

# Service Error Conditions

Sometimes a service might enter an error condition: a sensor stops working or the operating voltage for a peripheral is too low. It would be useful to indicate an error to a user and provide some information to identify the cause.

```cpp
struct JDServiceInfo
    {
        uint32_t service_class;
        uint8_t service_flags; 
        uint8_t advertisement_size;
        uint8_t advertisement_data[]; // optional additional data
    } __attribute((__packed__));
```

I propose that 1 bit is reserved in the service_flags field to indicate a hardware error. If the bit is set, the remaining bits of the flags field become the hardware error number, and the advertisement_data field contains an error message with more information, the size of which is dictated by the advertisement_size field.

This bit should only be used to indicate hardware errors that cannot be corrected by sending packets to the device. There will be a defined set of well known error numbers for use in the remaining 7 bits.

**Comment by mmoskal** [comment]
non-software errors -> let's call them hardware errors, not just errors, and define as errors that cannot be reset by sending packets to the device
