### ISSUE TITLE
Low cost microcontrollers

### ISSUE THREAD

**Issue by jamesadevine** [jacdac/jacdac#13]
This issue introduces a model for how low cost microcontrollers (sub 8 cents) could operate in the JACDAC ecosystem.

# Assumptions
* Have the capability to transmit but not receive.
* Have a factory flashed UUID.
* Can perform bus arbitration and error detection

# Observations

*  These microcontrollers will not be able to detect addressing collisions as they cannot receive, thus we will need to use an alternate addressing mechanism. 
* These microcontrollers cannot use the same service number as normal jacdac devices and must address a different service number within the control address namespace.

# Proposal

Transmit only devices should address data packets to address 0 and service_number 15. Full JACDAC devices will operate a service on this address and service_number combination that performs data packet routing for transmit only devices.

## Control Packets

For transmit only devices, control packets will retain the same structure and addressing. To indicate that the device is transmit only, the device_address field in the control packet should be set to 0:

| Field Size (bits)      	| Name           	| Description                                                                                        	|
|------------------------	|----------------	|----------------------------------------------------------------------------------------------------	|
| 64                     	| udid           	| The unique device identifier (udid) for the device.                                                	|
| 8                      	| device_address 	| MUST BE ZERO               	|
| 8                      	| device_flags   	|  A field for the ControlService indicating the state of a device.                                 	|
| N * ServiceInformation 	| data           	| The data field is filled with an array of HostServices operating on the device for use by the bus. 	|

## Data packets

As mentioned previously, data packets for transmit only devices should be addressed to device_address 0, and service_number 15.

Data packets must contain the UUID of the device that is used in the control packet allowing the routing of packets from transmit only devices.

| Field Size (bits)      	| Name           	| Description                                                                                        	|
|------------------------	|----------------	|----------------------------------------------------------------------------------------------------	|
| 64                     	| udid           	| The unique device identifier (udid) for the device. |
| 8 * (size - sizeof(udid)) 	| data           	| The data field is filled with an array of HostServices operating on the device for use by the bus. 	|

I think this should work without any significant modifications to the control layer.

**Comment by jamesadevine** [comment]
@finneyj

**Comment by jamesadevine** [comment]
So the proposal has changed slightly after a convo with @mmoskal 

We have decided to reserve another address (255) specifically for use by tx only devices.

Tx only devices will address 0,0 for control packets, and 255,service_number for data packets.

**Comment by pelikhan** [comment]
Is it 255,0 for control packets?

**Comment by jamesadevine** [comment]
No, all tx only devices would effectively share the address 255. Control packet addressing remains the same.
