### ISSUE TITLE
There is some microcontroller recommended for the sensor part

### ISSUE THREAD

**Issue by sabas1080** [jacdac/jacdac#2]
Hi

There is some microcontroller recommended for the part before the sensor or "slave", 

I imagine the scheme is:

sensor ->microcontroller->jacdac<---->jacdac->microcontroller

Thanks

**Comment by jamesadevine** [comment]
Hey @sabas1080...

The scheme is more like:

```microcontroller with sensor, running jacdac <--> aux cable <--> microcontroller running jacdac <--> aux cable <--> microcontroller running jacdac... etc.```

We're still in the research / definition phase, but the idea is that it will run on small 4 bit MCUs as well as more capable chips like SAMD21.

It currently runs on:

SAMD21/51, NRF51/52, STM32F4, STM32F1
