### ISSUE TITLE
Bus death method #1

### ISSUE THREAD

**Issue by teddyseyed** [jacdac/jacdac#3]
### Summary:

Unplugging a usb connected device while still connected to the jacdac bus seems to kill the bus entirely, until it is replugged, at which point anything else that was connected to the bus no longer connects except for the replugged device.

### Hardware Setup:

1. CPX running a Button service ([sample code here](https://makecode.com/_HrHAJDHVR6UA)).
2. CPX running an Accelerometer service connected to USB battery, with only ground and tx connected to audio jack ([sample code here](https://makecode.com/_ax50dxMczAfg)).
3. Arcade running logging service.

### Reproduction Steps:

1. Leave services / clients running and connected to the bus.
2. Unplug CPX Accelerometer from USB, but leave audio jack connected.
3. The bus has died!
4. Replug the USB battery into the CPX Accelerometer .
5. CPX acclerometer is connected to bus, but CPX Button no longer connected to bus.

**Comment by jamesadevine** [comment]
Thanks Teddy.

**Comment by jamesadevine** [comment]
Just for my info, are we filing JACDAC issues here @pelikhan @teddyseyed ?

**Comment by jamesadevine** [comment]
I think this is samd specific from the sounds of it? I certainly didn't robustly test CPX...

**Comment by jamesadevine** [comment]
I assume there are more than one bus death methods by the title? :smile:

**Comment by pelikhan** [comment]
Where do you want them?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesadevine** [comment]
It's probably best to unify all jacdac issues here, rather than across the billion codal repos! :smile:

**Comment by jamesadevine** [comment]
V-1 is not supported :smile: I'm sure V0 will bring a whole host of issues.
