### ISSUE TITLE
JDPacket structure

### ISSUE THREAD

**Issue by jamesadevine** [jacdac/jacdac#5]
I'm finalising what the final packet structure should be for a JACDAC packet.

Currently in V0 we have the following:

```cpp
struct JDPacket {
        uint16_t crc:12; // a cyclic redundancy check (currently crc12 is used).
        version:4; // identifies the version of the entire stack
        uint8_t session_id; // control is 0, devices are allocated address in the range 1 - 255
        uint8_t size; // the size, address, and crc are not included by the size variable. The size of a packet dictates the size of the data field.
        uint8_t data[];
    }
```

Recently I refactored the address (now known as a session identifier) to be per device rather than per service, decreasing the likelihood of duplicate session identifiers. The way a service is addressed is now through a combination of the session identifier and a service offset calculated through determining the position of the ServiceInformation in a ControlPacket. For example, take the following control packet:

```
ControlPacket
    session_id: 23
    unique_device_id: 1235464738
    ButtonService
        ...meta data...
    AccelerometerService
        ...meta data...
    ThermometerService
        ...meta data...
```

To address the Accelerometer service, a service offset of 1 and a session_id of 23 would be used. This means that the service offset also needs to be placed into a JDPacket to identify a service. 

Here is a proposed JDPacket revision incorporating the required information:

```cpp
struct JDPacket {
        uint8_t size:7; version:1; 
        uint16_t crc:12;
        service_number:4
        uint8_t address; // control is 0, devices are allocated address in the range 1 - 255
        uint8_t data[];
    }
```
There are a few major implications with this revision:

1. Maximum packet size is now 127 bytes (0...127) – we reserve 1 bit for version decreasing the possible value of size to 7 bits. An additional consideration is that CRC12 loses effectiveness at around 255 bytes:

<img width="539" alt="screenshot 2019-02-26 at 17 29 12" src="https://user-images.githubusercontent.com/4742697/53458712-0a563e00-39ec-11e9-91fd-0f58c7fdc4f0.png">

2. Only one bit is used to determine the current version – For v0, the version bit will be set to zero. This means that any future revisions will have to be substantial to warrant the version bit to be set. When set, we will drop any packets as the header format will likely be different.
3. A maximum of 16 services are allowed on each device – Previously the number of services was restricted by the address space to 254 values. This change would allow devices to host 16 services each, increasing the maximum amount of supported services to 4064 and more importantly reduce the potential of addressing collisions by reducing the need to allocate addresses.

**Comment by pelikhan** [comment]
What is the session thing? Isn’t it the device address?

**Comment by jamesadevine** [comment]
We can still call it address if you think it's more descriptive. See #4.

**Comment by pelikhan** [comment]
Looks reasonnable to me.

**Comment by jamesadevine** [comment]
@finneyj

**Comment by jamesadevine** [comment]
I think that we should enable devices to communicate packet sizes > 127 bytes. I propose that a packet size of 127 (0x7F) means that 255 bytes will be transmitted.

The main motivation for this change is that control packets won't be able to support 16 services if we want to place optional advertisement data inside the control packet.

Currently a control packet has the following structure:

```cpp
struct JDControlPacket
    {
        uint64_t serial_number;
        uint8_t device_address;
        uint8_t device_flags;
        uint8_t data[];
    } __attribute((__packed__));
```

With data containing N `JDServiceInfo` structs:

```cpp
struct JDServiceInfo
    {
        uint16_t service_flags: 8, service_status: 4, data_size: 4;
        uint32_t driver_class;  // the class of the driver
        uint8_t data[]; // optional additional data, maximum of 15 bytes
    } __attribute((__packed__));
```
The `data_size` field dictates the size of the `data` field for each `JDServiceInfo` struct.

The following images show the amount of bytes available per service given a maximum packet size.

<img width="414" alt="screenshot 2019-02-28 at 19 19 37" src="https://user-images.githubusercontent.com/4742697/53614189-dfa3eb00-3b8d-11e9-875d-bba3112232fc.png">

<img width="411" alt="screenshot 2019-02-28 at 19 19 54" src="https://user-images.githubusercontent.com/4742697/53614188-dfa3eb00-3b8d-11e9-977a-524039a562e3.png">

The main conclusion is that 127 bytes is not enough for 16 services.

@pelikhan how much advertisement data do you currently use per service in MakeCode?

**Comment by mmoskal** [comment]
Maybe only support even packet sizes?

**Comment by jamesadevine** [comment]
@mmoskal how do you mean? 0-126 and 254? Or pad every packet to an even number?

**Comment by mmoskal** [comment]
I was thinking pad every packet. But then again, it doesn't work so well with a "serial" service or similar. I'm concerned that if you need 130 bytes you need to transmit 255.

I would honestly do something like this: `bytes = size < 84 ? size : 84 + (size - 84) * 4`

size | bytes
----| ----
0 | 0
1 | 1
2 | 2
... | ...
82 | 82
83 | 83
84 | 84
85| 88
86 | 92
... | ...
126 | 252
127 | 256

If an application wants to send an arbitrary length data, then if it's longer than 84 bytes it will have to broken up (with your solution that limit is 127). The breaking up isn't very difficult (or rather will be far from the most difficult part) and can be part of jacdac library.

**Comment by jamesadevine** [comment]
On todays call we decided that dropping the version bit, and returning the size field to 8 bits is the most sensible way forward. This allows us to address 255 bytes once again. 

For future proofing, a new protocol version would use a different crc polynomial.

**Comment by jamesadevine** [comment]
To summarise, a JACDAC packet will have the following structure:

```cpp
struct JDPacket {
        uint16_t crc:12;
        service_number:4
        uint8_t address; // control is 0, devices are allocated address in the range 1 - 254
        uint8_t size;
        uint8_t data[];
    }
```
The implications of this revision are:

1. Maximum packet size is 254 bytes (0...254) – We will not support greater packet sizes as CRC12 loses effectiveness at around 255 bytes:

<img width="539" alt="screenshot 2019-02-26 at 17 29 12" src="https://user-images.githubusercontent.com/4742697/53458712-0a563e00-39ec-11e9-91fd-0f58c7fdc4f0.png">

2. The computation of the crc will dictate the version – as well as including the serial_number of the transmitting device in the crc calculation, the polynomial used for crc calculation will change from version to version. This means that incompatible JACDAC versions will see packets from newer versions as corrupt.

3. A maximum of 16 services are allowed on each device – Previously the number of services was restricted by the address space to 254 values. This change would allow devices to host 16 services each, increasing the maximum amount of supported services to 4064 and more importantly reduce the potential of addressing collisions by reducing the need to allocate addresses.

**Comment by jamesadevine** [comment]
complete
