### ISSUE TITLE
Bus NACK?

### ISSUE THREAD

**Issue by jamesadevine** [jacdac/jacdac#8]
For V0, I'm contemplating the addition of a bus NACK to indicate that packet reception has failed by one or more devices.

The specific case I'm thinking about is when two devices transmit at the same time:

<img width="440" alt="screenshot 2019-03-01 at 09 21 41" src="https://user-images.githubusercontent.com/4742697/53654777-6f37b100-3c03-11e9-94f3-8f846a70cc46.png">

In the case of UART hardware, some hardware modules may detect the condition when two (or more) devices are driving the bus, and some may not. For devices that are bit-banging and not using UART hardware, I don't think they will be able to detect this condition at all.

The big implication of this decision is to decide whether the bus is lossy or if some reliability guarantees are provided: if a device doesn't receive a NACK on the bus, they can assume that the packet was received by all devices.

Thoughts?

**Comment by mmoskal** [comment]
I don't think you can assume everyone got a packet of there is no NACK. Device might have blocked irqs for too long etc. Also if one device is malfunctioning it is easier to accidently stop the entire network with this. I could easily see low speed devices NACKing all high speed packets.

**Comment by jamesadevine** [comment]
agreed, sound like a bad idea to have a bus nack.
