### ISSUE TITLE
Zero Length Packets

### ISSUE THREAD

**Issue by jamesadevine** [jacdac/jacdac#9]
Do we want/need the ability to send zero length packets in JACDAC?

With a size field of 8 bits, we have 255 possible values: 0 - 254. Therefore the maximum packet size is 254 bytes.

If we think it's important to support 255 bytes, we could make it so that zero length packets are not possible and that the value of `size` is `size + 1` (i.e. 0 = 1, 1 = 2 etc.)

Thoughts?

**Comment by pelikhan** [comment]
Is there a scenario for this? Some kind of ping? Seems like control packets already do that.

**Comment by jamesadevine** [comment]
I guess you could implement an ACK using a ZLP, but normally you want to know if it's an ack by having a status byte...

**Comment by mmoskal** [comment]
I would say keep it simple and allow zlp

**Comment by mmoskal** [comment]
BTW you have 256 possible values

**Comment by jamesadevine** [comment]
Hahahahaha, I'm big dingus... 0 - 255 it is.
